### ISSUE TITLE
A way to provide custom Meteor commands

### ISSUE THREAD

**Issue by mitar** [MeteorCommunity/discussions#33]
Currently, one has to provide a [Meteor fork to provide custom Meteor commands](http://practicalmeteor.com/using-meteor-publish-release-to-extend-the-meteor-command-line-tool/), but there should be a better way.

Relevant ticket: https://github.com/meteor/meteor/issues/916

**Comment by raix** [comment]
is it a duplicate of https://github.com/MeteorCommunity/discussions/issues/9?

**Comment by mitar** [comment]
Oh, true.
