### ISSUE TITLE
Provide a way to say which fields in Meteor.user() you are interested

### ISSUE THREAD

**Issue by mitar** [MeteorCommunity/discussions#34]
I noticed that many novice Meteor programmers use `Meteor.user()` to check if user is logged in, or to get one field out. But they do not know that `Meteor.user()` make a dependency on the whole document, so anything changes, the template rendering is rerun.

Providing a way to filter fields (in PeerLibrary fork we are using simple dict as a parameter which is passed to `fields` in the query) would hint to developers that they can do that and it would be easy to instruct them to do it.

Related: https://github.com/meteor/meteor/issues/1561

**Comment by zimme** [comment]
From avital's comment I don't believe MDG will change this function.

So I believe it's a task for the educational factions of the community to teach users of meteor about this.

**Comment by mitar** [comment]
I made a package for this: https://github.com/peerlibrary/meteor-user-extra

It also allows one to use `Metor.userId()` everywhere on the server-side. So you can have unified code.
