### ISSUE TITLE
Packaging libraries with global variables

### ISSUE THREAD

**Issue by physiocoder** [MeteorCommunity/discussions#60]
I'm trying to package a couple of libraries (fabric.js and event.js). They both declare global variables with `var fabric` at the top of the file instead of the pattern:

```
(function() {
    var fabric;
    ...
    // if we are in a browser and not in an AMD or CommonJs environment
    window.fabric = fabric;
}());
```

this means that my `exports.js` isn't able to access the variable I want to export since it's wrappped in a closure by Meteor packaging system. I sent a pull request to library author to add:

```
if(window !== undefined) window.fabric = fabric;
```

in code and make sure the variable became global, but was wondering if there is a way not to ask for this library modification in order to integrate in Meteor.

**Comment by dandv** [comment]
Starting with Meteor 1.3, 3rd party libraries can be used directly from npmjs.
