### ISSUE TITLE
Teoria

### ISSUE THREAD

**Issue by skarborg** [MeteorCommunity/discussions#67]
Gentlemen

Please give me access to organization and fork https://github.com/saebekassebil/teoria

I would like to create package

Thanks

**Comment by splendido** [comment]
Just foked and invited you to the `teoria` team which has enough rights on the [teoria](https://github.com/MeteorPackaging/teoria) repository.

Please follow the [Step by Step Guide](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki#step-by-step-guide) but also try to read the other pages you'll find on the wiki.

Let us know when you're ready!

P.S: the correct track was [MeteorPackaging/discussions/issues](https://github.com/MeteorPackaging/discussions/issues), are you by chance coming from some broken link?

**Comment by skarborg** [comment]
Sorry, probably just browsed to wrong link.

**Comment by dandv** [comment]
Starting with Meteor 1.3, 3rd party libraries can be used directly from npmjs.
