### ISSUE TITLE
Moment-recur

### ISSUE THREAD

**Issue by gilbertwat** [MeteorCommunity/discussions#70]
Hi community!

I have found the moment-recur library very useful and decided to do a meteor integration. I have (forked)[https://github.com/gilbertwat/moment-recur/tree/meteor_integration] the library and followed the (instructions)[https://github.com/MeteorCommunity/discussions/issues/14]. I currently published under my account. Anything to do to proceed?

**Comment by splendido** [comment]
Hi @gilbertwat, 
this seems a good package to be published as `momentjs:recur`!

Recently we have investigated the use of [autopublish.meteor.com](http://autopublish.meteor.com/) which is prooving very effective!
Lets have a look at the [wiki](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki)

Could you please open an issue about this integration [here](https://github.com/MeteorPackaging/discussions/issues) so we can then proceed forward?

**Comment by splendido** [comment]
I've just seen [your PR](https://github.com/c-trimm/moment-recur/pull/32) to get an official integration.
From the previous attempts we had, I'd say it's not a good idea to ask maintainers to install/run meteor on  their machines.
We'd better do something on the lines of the [successful integrations](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/Known-Attempts-to-get-Official-Integration)

**Comment by dandv** [comment]
Starting with Meteor 1.3, 3rd party libraries can be used directly from npmjs.
