### ISSUE TITLE
Use Lodash instead of Underscore

### ISSUE THREAD

**Issue by raix** [MeteorCommunity/discussions#8]
There's an open issue on meteor https://github.com/meteor/meteor/issues/1009 that would be nice to keep track of. _(its the most upvoted closed issue in meteor so I've set community agree)_

Please vote there!

Why:
@jdalton
- Better documentation
- Consistency
- Compatibility
- Performance
- Customization
- Support, & more features & repo activity
- It's also easy to switch, simply swapping module names (with compat paths if necessary)
- Follows semver

Waiting:
@glasser:

> Lodash looks great. But just like every time we upgrade a Node minor
> version, the day I swap in lodash will be a day where I do a full automated
> and manual QA of Meteor. Which is something we're trying to make more and
> more automated, but we're not there yet.

_Due to this comment I assume MDG agree_

**Comment by ai10** [comment]
Lodash.min is 50kb, underscore.min is 16kb?

**Comment by pihentagy** [comment]
https://raw.githubusercontent.com/lodash/lodash/3.7.0/lodash.min.js is 18k

**Comment by jdalton** [comment]
It's as if lodash has more functionality/features :grinning:

**Comment by Sivli-Embir** [comment]
> It's as if lodash has more functionality/features.

I have had to use a number of other packages to fill the gap. I expect my total underscore plus friends min is well over 50kb. 18k is amazing.

:+1: +1 :+1:

**Comment by dandv** [comment]
Since the meteor/meteor GitHub issue is open now that MDG accepts feature requests via GitHub, I've update the OP and will close the issue here.

**Comment by rclai** [comment]
Hey guys, so I've created a repository with a solution to actually replace underscore under the hood with lodash:
https://github.com/rclai/meteor-lodash-replace-underscore
Please feel free to contribute or let me know of any suggestions.

**Comment by zimme** [comment]
@rclai: :+1:

**Comment by veob** [comment]
Hey, guys. 
https://raw.githubusercontent.com/lodash/lodash/3.7.0/lodash.min.js is 50kB, not 18kB (latest too). What am I doing wrong?

**Comment by jdalton** [comment]
It's gzipped to 18kb.

Since folks seem to be concerned with file size you all may dig that lodash v4 will ship with a 4kb build (thats +1kb smaller than Underscore) while still supporting Backbone and packed with 60+ methods.

**Comment by veob** [comment]
Ah, okay. Thank you :+1:

**Comment by jdalton** [comment]
Since folks seem to be concerned with file size, lodash v4 will ship with a 4kb build (thats more than 1kb smaller than Underscore) while still supporting Backbone and packed with 60+ methods.
